spring.application.name=mini-erp-simulator

spring.datasource.url=jdbc:mysql://localhost:3306/mini_erp
spring.datasource.username=root
spring.datasource.password=Vasco1token2!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080